### ISSUE TITLE
on a clean install, docker-compose up returns error for kafka container

### ISSUE THREAD

**Issue by cslovell** [usc-isi-i2/dig-etl-engine#188]
Creating dig_elasticsearch_1   ... 
Creating dig_zookeeper_1       ... 
Creating dig_dig_etl_engine_1  ... done
Creating dig_kibana_1          ... done
Creating dig_digui_1           ... done
Creating dig_sandpaper_1       ... done
Creating dig_kafka_1           ... error
Creating dig_mydig_ws_1        ... done
Creating dig_kibana_1          ... 
Creating dig_nginx_1           ... done

ERROR: for dig_kafka_1  user specified IP address is supported only when connecting to networks with user configured subnets
Creating dig_mydig_ws_1        ... 
Creating dig_nginx_1           ... 

ERROR: for kafka  user specified IP address is supported only when connecting to networks with user configured subnets
ERROR: Encountered errors while bringing up the project.

**Comment by GreatYYX** [comment]
Could you please paste the result of `docker network ls` here? There should be a docker network named `dig_dig_net`.

For Kafka, because it specified a static ip, if this ip conflicts with your host or other docker network, please change it by modifying docker-compose.yml file:

```
...

  kafka:
    image: wurstmeister/kafka
...
    networks:
      dig_net:
        ipv4_address: 172.19.0.200

...
networks:
  dig_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16

...
```
Replace `172.19.0.200` to `172.30.0.200`, `172.19.0.0/16` to `172.30.0.0/16` (30 can be any integer between 0 to 255).
